### P1 — Regression

In [ ]:
from mibici.modeling.p1 import load_p1_data
from mibici.features import build_p1_features
import pandas as pd

daily_demand = load_p1_data()
feature_data = build_p1_features(daily_demand)

train_data = feature_data.loc[
    feature_data["date"] < "2026-09-01"
].copy()

validation_data = feature_data.loc[
    feature_data["date"] >= "2026-09-01"
].copy()

2026-10-18 00:14:46.574 | INFO     | mibici.config:<module>:11 - PROJ_ROOT path is: /home/jovyan/notebooks/mibici/mibici_predictions

In [3]:
station_train_summary = (
    train_data.groupby("station_id")["departures"]
    .agg(["count", "median", "mean", "max"])
    .sort_values("max", ascending=False)
)

display(station_train_summary.head(15))

            count  median        mean  max
station_id
51             92   324.5  322.793478  520
50             87   163.0  165.770115  338
35             92   140.5  119.293478  336
54             91   151.0  165.549451  319
194            86   138.0  136.116279  317
271            92   191.5  185.673913  287
11             92   178.5  168.021739  270
52             81   143.0  137.913580  200
36             92    97.5  103.576087  199
38             92   120.0  117.684783  194
260            89   119.0  113.640449  192
196            92    64.0   73.130435  189
396            92    34.5   38.728261  183
28             92    96.0   99.369565  178
75             92   109.0   98.750000  159

In [5]:
import pandas as pd

for station_id in [51, 396, 196]:
    station_data = (
        train_data.loc[train_data["station_id"].eq(station_id)]
        .sort_values("date")
    )

    peak_date = station_data.loc[
        station_data["departures"].idxmax(), "date"
    ]

    print(f"\nEstación {station_id}")

    display(
        station_data.loc[
            station_data["date"].between(
                peak_date - pd.Timedelta(days=3),
                peak_date + pd.Timedelta(days=3),
            ),
            ["station_id", "date", "departures", "day_of_week"],
        ]
    )

Estación 51

      station_id       date  departures  day_of_week
5691          51 2026-07-01         314            2
5692          51 2026-07-02         318            3
5693          51 2026-07-03         321            4
5694          51 2026-07-04         520            5
5695          51 2026-07-05         359            6
5696          51 2026-07-06         421            0
5697          51 2026-07-07         358            1

Estación 396

       station_id       date  departures  day_of_week
44178         396 2026-06-03          46            2
44179         396 2026-06-04          52            3
44180         396 2026-06-05          35            4
44181         396 2026-06-06         183            5
44182         396 2026-06-07         110            6
44183         396 2026-06-08          35            0
44184         396 2026-06-09          27            1

Estación 196

       station_id       date  departures  day_of_week
21274         196 2026-06-03          75            2
21275         196 2026-06-04          75            3
21276         196 2026-06-05          46            4
21277         196 2026-06-06         189            5
21278         196 2026-06-07         181            6
21279         196 2026-06-08          54            0
21280         196 2026-06-09          72            1

Estación 51: se inspeccionó el máximo de 520 salidas y sus días
cercanos. El conteo es elevado respecto a esos días, pero no se
identificó evidencia de error. Se conserva el registro.